import * as vscode from 'vscode'
import {debugLog} from '../core/debug'
import {manifestKey, removeManifestEntry} from './manifest'
import {getWorkspaceFolder} from '../core/utils'

/**
 * CompiledDocLifecycle — manages the open/sync/close lifecycle of
 * synthetic PHP documents generated by the Blade compiler.
 * Extracted from diagnostics.ts to isolate tab orchestration
 * from diagnostic mapping logic.
 */

const autoOpenedCompiledUris = new Set<string>()
const userOpenedCompiledUris = new Set<string>()

export function markCompiledAsUserOpened(uri: vscode.Uri): void {
    userOpenedCompiledUris.add(uri.toString())
    autoOpenedCompiledUris.delete(uri.toString())
}

export function markCompiledAsAutoOpened(uri: vscode.Uri): void {
    if (!userOpenedCompiledUris.has(uri.toString())) {
        autoOpenedCompiledUris.add(uri.toString())
    } else {
        debugLog(`markCompiledAsAutoOpened: skipping ${uri.toString()} (user-opened)`)
    }
}

export async function openCompiledDoc(uri: vscode.Uri, bladePath: string): Promise<vscode.TextDocument | undefined> {
    try {
        const compiledDoc = await vscode.workspace.openTextDocument(uri)
        markCompiledAsAutoOpened(uri)

        return compiledDoc
    } catch (error) {
        debugLog(`failed to open compiled doc for ${bladePath}: ${String(error)}`)

        return undefined
    }
}

export async function syncCompiledDoc(compiledDoc: vscode.TextDocument, content: string, save: boolean): Promise<boolean> {
    if (compiledDoc.getText() === content) {
        return false
    }

    const edit = new vscode.WorkspaceEdit()
    edit.replace(
        compiledDoc.uri,
        new vscode.Range(new vscode.Position(0, 0), compiledDoc.positionAt(compiledDoc.getText().length)),
        content,
    )

    if (await vscode.workspace.applyEdit(edit)) {
        if (save) {
            await compiledDoc.save()
        }
    }

    return true
}

async function deleteCompiledFile(compiledUriStr: string, bladeUriStr: string): Promise<void> {
    const bladePath = vscode.Uri.parse(bladeUriStr).fsPath
    const workspaceRoot = getWorkspaceFolder(vscode.Uri.parse(bladeUriStr))?.uri.fsPath

    try {
        await vscode.workspace.fs.delete(vscode.Uri.parse(compiledUriStr))
        await removeManifestEntry(workspaceRoot ? manifestKey(bladePath, workspaceRoot) : bladePath)
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        debugLog(`deleteCompiledFile failed for ${bladePath}: ${message}`)
    }
}

export interface CompiledDocEntry {
    bladeUri    : string
    compiledDoc : vscode.TextDocument | undefined
    compiledUri : vscode.Uri | undefined
}

export async function closeCompiledTab(
    entry: CompiledDocEntry,
    wipeContent = false,
): Promise<void> {
    const compiledUri = entry.compiledUri

    if (!compiledUri) {
        return
    }

    const key = compiledUri.toString()

    if (userOpenedCompiledUris.has(key)) {
        return
    }

    let closed = false

    if (autoOpenedCompiledUris.has(key)) {
        for (const group of vscode.window.tabGroups.all) {
            for (const tab of group.tabs) {
                if (
                    tab.input instanceof vscode.TabInputText
                    && tab.input.uri.toString() === key
                ) {
                    await vscode.window.tabGroups.close(tab, true)
                    closed = true
                    break
                }
            }

            if (closed) {
                break
            }
        }

        autoOpenedCompiledUris.delete(key)
    }

    if (wipeContent) {
        entry.compiledDoc = undefined
        entry.compiledUri = undefined
        await deleteCompiledFile(key, entry.bladeUri)
    } else {
        entry.compiledDoc = undefined
    }
}

export function clearAutoOpenedCompiledUri(uri: vscode.Uri): void {
    autoOpenedCompiledUris.delete(uri.toString())
}
